"""add_public_key_to_users

Revision ID: 4e8cbbfce1eb
Revises: 28550eeeff51
Create Date: 2026-05-17 14:27:26.336573+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8cbbfce1eb'
down_revision = '28550eeeff51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_key')
    # ### end Alembic commands ###
