"""add_password_hash_to_users

Revision ID: b69f20a5be61
Revises: 20260405_1010
Create Date: 2026-04-09 08:05:14.383978+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b69f20a5be61'
down_revision = '20260405_1010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasets_created_at'), table_name='datasets')
    op.add_column('feed_events', sa.Column('event_metadata', sa.JSON(), nullable=True))
    op.drop_column('feed_events', 'metadata')
    op.drop_constraint(op.f('profiles_user_id_key'), 'profiles', type_='unique')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_facebook_oauth_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_google_oauth_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_facebook_oauth_id'), table_name='users')
    op.create_index(op.f('ix_users_facebook_oauth_id'), 'users', ['facebook_oauth_id'], unique=True)
    op.drop_index(op.f('ix_users_google_oauth_id'), table_name='users')
    op.create_index(op.f('ix_users_google_oauth_id'), 'users', ['google_oauth_id'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_google_oauth_id'), table_name='users')
    op.create_index(op.f('ix_users_google_oauth_id'), 'users', ['google_oauth_id'], unique=False)
    op.drop_index(op.f('ix_users_facebook_oauth_id'), table_name='users')
    op.create_index(op.f('ix_users_facebook_oauth_id'), 'users', ['facebook_oauth_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_google_oauth_id_key'), 'users', ['google_oauth_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_facebook_oauth_id_key'), 'users', ['facebook_oauth_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('profiles_user_id_key'), 'profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.add_column('feed_events', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('feed_events', 'event_metadata')
    op.create_index(op.f('ix_datasets_created_at'), 'datasets', ['created_at'], unique=False)
    # ### end Alembic commands ###
