"""add_banner_to_profiles

Revision ID: de2de280e099
Revises: 20260513_1600
Create Date: 2026-05-11 09:00:19.104360+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2de280e099'
down_revision = '20260513_1600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('banner_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('banner_s3_key', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('banner_thumbnail_s3_key', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('banner_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('banner_content_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'banner_content_type')
    op.drop_column('profiles', 'banner_uploaded_at')
    op.drop_column('profiles', 'banner_thumbnail_s3_key')
    op.drop_column('profiles', 'banner_s3_key')
    op.drop_column('profiles', 'banner_url')
    # ### end Alembic commands ###
