"""add_message_status_fields

Revision ID: 28550eeeff51
Revises: de2de280e099
Create Date: 2026-05-11 15:55:54.435250+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28550eeeff51'
down_revision = 'de2de280e099'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_conversations_direct_pair'), table_name='conversations', postgresql_where="(((type)::text = 'direct'::text) AND (direct_user_low_id IS NOT NULL))")
    op.drop_index(op.f('ix_friend_requests_pending_pair'), table_name='friend_requests', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_constraint(op.f('uq_groups_slug'), 'groups', type_='unique')
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=True)
    op.add_column('messages', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_notebooks_group_published_created'), table_name='notebooks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notebooks_group_published_created'), 'notebooks', ['group_id', 'is_published', 'created_at'], unique=False)
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'delivered_at')
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_groups_slug'), 'groups', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_friend_requests_pending_pair'), 'friend_requests', ['requester_id', 'addressee_id'], unique=True, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index(op.f('uq_conversations_direct_pair'), 'conversations', ['direct_user_low_id', 'direct_user_high_id'], unique=True, postgresql_where="(((type)::text = 'direct'::text) AND (direct_user_low_id IS NOT NULL))")
    # ### end Alembic commands ###
